name: Node.js CI and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Adjust Node.js version as needed

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./build basim-reactapp.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Run Tests
        run: npm test
